// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebAppiGraphql.Services;

namespace WebAppiGraphql.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20191117123500_Phones_Add_To_People")]
    partial class Phones_Add_To_People
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.0-preview1.19506.2");

            modelBuilder.Entity("WebAppiGraphql.Models.People", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnName("active")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Created")
                        .HasColumnName("created")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnName("name")
                        .HasColumnType("TEXT")
                        .HasMaxLength(100);

                    b.Property<DateTime>("Updated")
                        .HasColumnName("updated")
                        .HasColumnType("TEXT");

                    b.HasKey("Id")
                        .HasName("id");

                    b.ToTable("peoples");
                });

            modelBuilder.Entity("WebAppiGraphql.Models.Phone", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Ddd")
                        .HasColumnName("ddd")
                        .HasColumnType("TEXT")
                        .HasMaxLength(3);

                    b.Property<string>("Number")
                        .HasColumnName("number")
                        .HasColumnType("TEXT")
                        .HasMaxLength(10);

                    b.Property<int>("PeopleId")
                        .HasColumnName("peopleid")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id")
                        .HasName("id");

                    b.HasIndex("PeopleId");

                    b.ToTable("phones");
                });

            modelBuilder.Entity("WebAppiGraphql.Models.Phone", b =>
                {
                    b.HasOne("WebAppiGraphql.Models.People", "People")
                        .WithMany("Phones")
                        .HasForeignKey("PeopleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
